In [6]:
import os, sys, json
sys.path.append("../")
from own_utils.oss_new import OssUtil
from own_utils.sql_python_utils import *
from own_utils.H5_utils import H5_utils
import json
import numpy as np
from multiprocessing import Pool
import pandas as pd

In [ ]:
country = 'new'
environment = "testing"
bucket = "cv-develop"
table_buried_point = 'id_sdk_liveness_buried_points_202504' 
table_detection = 'id_sdk_liveness_detection'
oss = OssUtil(country = country, environment = environment, bucket = bucket)
connect = Connector(country = country, environment = environment, database = "cv")
h5 = H5_utils(connect = connect, oss = oss, table_buried_point = table_buried_point, table_detection = table_detection)

In [9]:
def mediapipe106_h5_file_analysis(id):
    try:
        h5_file_detail = oss.get_h5_file(oss_id= id).split("\n")
        client = None
        backend = None
        detector_loading = []
        pfld_106_loading = []
        detector_init = []
        pfld_106_init = []
        detector_prediction = []
        pfld_106_prediction = []
        overall_processing = []
        for line in h5_file_detail:
            if 'client_type' in line:
                client = line.split('client_type')[-1].strip()
            if 'Backend' in line:
                backend = line.split('Backend')[-1].strip() 
            if 'detector init' in line:
                detector_init.append(int(line.split('detector init')[-1].strip()))
            if '106_pfld init' in line:
                pfld_106_init.append(int(line.split('106_pfld init')[-1].strip()))
            if '106_pfld loading ' in line:
                pfld_106_loading.append(int(line.split('106_pfld loading')[-1].strip()))
            if 'detector loading' in line:
                detector_loading.append(int(line.split('detector loading')[-1].strip()))
            if 'dectector prediction' in line:
                detector_prediction.append(int(line.split('dectector prediction')[-1].strip()))
            if '106_plfd prediction' in line:
                pfld_106_prediction.append(int(line.split('106_plfd prediction')[-1].strip()))
            if 'overall processing' in line:
                overall_processing.append(int(line.split('overall processing')[-1].strip()))
        
        detector_loading = int(np.mean(detector_loading)) if detector_loading else 'not found'
        pfld_106_loading = int(np.mean(pfld_106_loading)) if pfld_106_loading else 'not found'
        detector_init = int(np.mean(detector_init)) if detector_init else 'not found'
        pfld_106_init = int(np.mean(pfld_106_init)) if pfld_106_init else 'not found'
        detector_prediction = int(np.mean(detector_prediction)) if detector_prediction else 'not found'
        pfld_106_prediction = int(np.mean(pfld_106_prediction)) if pfld_106_prediction else 'not found'
        overall_processing = int(np.mean(overall_processing)) if overall_processing else 'not found'
        
        return (client, backend, detector_loading, pfld_106_loading, detector_init, pfld_106_init, detector_prediction, pfld_106_prediction, overall_processing)
    except Exception:
        return None

In [10]:
def process_row(row_input):
    # Assuming 'row' is a dictionary-like object containing necessary data
    index, row, new_columns = row_input
    result = None    
    if isinstance(row['H5_file'], str) and row['H5_file'].endswith(".txt") and row['H5_file'] != "no H5 file":
        oss_id = row['H5_file']
        result = mediapipe106_h5_file_analysis(id = oss_id)
        if not result:
            result = ['no H5 file'] * len(new_columns) 
    else:
        result = ['no H5 file'] * len(new_columns)
        
    return (index, result)

def multiprocess_row(df, new_columns, number_worker = 4):
    df = df.reset_index(drop= True)
    tasks = [(index, row.to_dict(), new_columns) for index, row in df.iterrows()]

    # Set up multiprocessing
    with Pool(processes = number_worker) as pool:
        results = pool.map(process_row, tasks)

    # Update DataFrame with results
    for index, update in results:
        df.loc[index, new_columns] = update

    return df

In [11]:
query = f"""
SELECT *
FROM cv.id_sdk_liveness_result
WHERE user_id in ("zox586f5d", "zoxf02e03", "zox060769", "zoxa4926a", "zoxbee50a", "zox6f7eed")
"""
liveness_data = connect.query(query=query)

print(f"Shape : {liveness_data.shape}")
liveness_data.drop_duplicates(subset= ['liveness_id'], inplace= True, keep= 'last')
liveness_data['data'] =  liveness_data['data'].apply(lambda x: json.loads(x))
liveness_data['ext_info'] =  liveness_data['ext_info'].apply(lambda x: json.loads(x))
liveness_data['liveness_result_msg'] = liveness_data['ext_info'].apply(lambda x: x.get("errMsg", None))
liveness_data['liveness_result_code'] = liveness_data['ext_info'].apply(lambda x: x.get("code", None))
liveness_data['sdk_version'] = liveness_data['ext_info'].apply(lambda x: x.get("sdk_version", None))
liveness_data['system'] = liveness_data['ext_info'].apply(lambda x: x.get("system", None))
liveness_data['deviceInfo'] = liveness_data['ext_info'].apply(lambda x: x.get("deviceInfo", {}).get('source', None))
liveness_result_df = liveness_data[['liveness_id', "create_time", 'partner_id', 'user_id', 'liveness_result_msg', 'liveness_result_code', 'sdk_version', 'system', 'deviceInfo']]
liveness_count_df = liveness_result_df.groupby('user_id').size().reset_index(name = 'user_liveness_count')
liveness_result_df = liveness_result_df.merge(right= liveness_count_df, on= 'user_id', how= 'inner')
user_id_unique = str(tuple(liveness_result_df['user_id'].unique()))
liveness_id_unique = str(tuple(liveness_result_df['liveness_id'].unique()))
buried_detail_df = h5.get_buried_detail(liveness_id= liveness_id_unique)
df = liveness_result_df.merge(buried_detail_df, on = 'liveness_id', how = 'left')
df = df[df["deviceInfo"] == "android-app"].drop(columns = ["detector_type", "create_time", "user_liveness_count", "partner_id"]).reset_index(drop = True)
df = df.drop_duplicates(subset= ['liveness_id'], keep= 'last').reset_index(drop = True)
new_column = ['client', 'backend', 'detector_loading', "pfld_106_loading", "detector_init", "pfld_106_init", "detector_prediction", "pfld_106_prediction", "overall_processing"]
result = None
for index, row in df.iterrows():
    oss_id = row['H5_file']
    result = mediapipe106_h5_file_analysis(id = oss_id)
    df.loc[index, new_column] = result
df

Shape : (6, 12)
Getting buried detail................
Getting buried detail done!!!

,liveness_id,user_id,liveness_result_msg,liveness_result_code,sdk_version,system,deviceInfo,H5_file,client,backend,detector_loading,pfld_106_loading,detector_init,pfld_106_init,detector_prediction,pfld_106_prediction,overall_processing
0,144a847b-5aba-403b-8273-f85249fbbc81,zox01e56f,活体认证成功,200,2.2.1.1,h5,android-app,d41830e60fdb3eb98da5e9d4ed8e4f97.txt,None,None,not found,not found,not found,not found,not found,not found,not found
1,a06c8c9f-d96f-46c9-a8cb-5d4ab2aec435,zox3ac708,活体认证成功,200,2.2.1.1,h5,android-app,4d4647282dc43cc3a82214ed272df06d.txt,None,None,not found,not found,not found,not found,not found,not found,not found
2,5da2571c-1c0b-4867-878b-0a828818b9a1,zox1c44dd,活体认证成功,200,2.2.1.1,h5,android-app,067b156426e03f02a7d7b9fc9135b52b.txt,None,None,not found,not found,not found,not found,not found,not found,not found
3,d14112ce-a779-48ad-9dd5-f920c85cc5a8,zox4c23ef,活体认证成功,200,2.2.1.1,h5,android-app,c1aaca96acfb351d859508355505befa.txt,None,None,not found,not found,not found,not found,not found,not found,not found
4,71e741e2-3b92-42af-85f6-34ed4e264568,zox244e7f,活体认证成功,200,2.2.1.1,h5,android-app,4b2f24e4992933d993805c4487723512.txt,None,None,not found,not found,not found,not found,not found,not found,not found
5,7d54ebd6-cbcd-4eff-99c3-233a048368c5,zoxf9e115,活体认证成功,200,2.2.1.1,h5,android-app,34137448a10e39d7b56c58dac010f327.txt,None,None,not found,not found,not found,not found,not found,not found,not found

In [5]:
user = "zox01e56f"
query = f"""
SELECT *
FROM cv.mx_sdk_liveness_result
WHERE user_id = "{user}"
"""
liveness_result_data = connect.query(query=query)
print(liveness_result_data['ext_info'].to_list())
liveness_result_data

KeyboardInterrupt:

In [7]:

query = f"""
SELECT *
FROM cv.id_sdk_liveness_buried_points_202504
WHERE user_id = "{user}"
"""
buried_data = connect.query(query=query)
print(buried_data['data'].to_list()[0])
print(buried_data['ext_info'].to_list()[-1])
print(buried_data['data'].to_list()[2])
buried_data

第0次活体。手机品牌：vivo，手机型号：V2247，系统版本：14，系统sdk版本：34，系统语言：zh，CPU架构：arm64-v8a，GPU渲染器：Adreno (TM) 610，GPU供应商：Qualcomm，GPU版本：OpenGL ES-CM 1.1，WebView版本：134.0.6998.135
{"log_file_path": "/app/logs/8ffa776ef1393ba8862b66df0f52020d.txt"}
打开网页耗时：7979

,id,request_params,transaction_id,action,liveness_id,data,create_time,update_time,ext_info,user_id,sdk_version
0,2849,None,7314ff2e520730858a9d5c8c001c651b,Log,,第0次活体。手机品牌：vivo，手机型号：V2247，系统版本：14，系统sdk版本：34，...,2025-04-01 16:46:29.797900,2025-04-01 16:46:29.797700,None,zox6f7eed,AAR-2.0.2
1,2850,None,f0b3a6d8b889387eaa7ff1cce809fa4d,Log,,拿到livenessId：05c6ce94-20de-4e7a-88f5-b51433b126bf,2025-04-01 16:46:31.066600,2025-04-01 16:46:31.066500,None,zox6f7eed,AAR-2.0.2
2,2851,None,26fe21fb4222361a8baaa53384d48804,网页打开成功,05c6ce94-20de-4e7a-88f5-b51433b126bf,打开网页耗时：7979,2025-04-01 16:46:37.280200,2025-04-01 16:46:37.280100,None,zox6f7eed,AAR-2.0.2
3,2855,None,eac6aeb6b1fd343ba74f710ba306b027,H5_log_load_URL,05c6ce94-20de-4e7a-88f5-b51433b126bf,加载活体H5URL成功,2025-04-01 16:46:37.503900,2025-04-01 16:46:37.503700,"{""partner_id"": ""90""}",zox6f7eed,2.2.1.1
4,2856,None,1e45b5ef9a473c5bb81b1977ddd3ed86,H5_log_user_device_system_info,05c6ce94-20de-4e7a-88f5-b51433b126bf,Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:5...,2025-04-01 16:46:37.506300,2025-04-01 16:46:37.506100,"{""partner_id"": ""90""}",zox6f7eed,2.2.1.1
5,2857,None,89e3f63973f23b7581c672603e79a040,H5_log_detector_type,05c6ce94-20de-4e7a-88f5-b51433b126bf,mediapipe106,2025-04-01 16:46:37.508700,2025-04-01 16:46:37.508600,"{""partner_id"": ""90""}",zox6f7eed,2.2.1.1
6,2858,None,b1c46b3bbc123a6cb0beb9b06f37cb80,H5_log_device_system_info,05c6ce94-20de-4e7a-88f5-b51433b126bf,iosundefined,2025-04-01 16:46:37.571900,2025-04-01 16:46:37.571700,"{""partner_id"": ""90""}",zox6f7eed,2.2.1.1
7,2859,None,21e41896fc0134898f38c329068e1a7c,H5_log_live_Count,05c6ce94-20de-4e7a-88f5-b51433b126bf,进入活体次数：1,2025-04-01 16:46:37.580900,2025-04-01 16:46:37.580800,"{""partner_id"": ""90""}",zox6f7eed,2.2.1.1
8,2860,None,e63163f60f5e31d3b2e90837caac7fb0,H5_log_camera_SUCCESS,05c6ce94-20de-4e7a-88f5-b51433b126bf,相机打开成功,2025-04-01 16:46:37.878500,2025-04-01 16:46:37.878300,"{""partner_id"": ""90""}",zox6f7eed,2.2.1.1
9,2861,None,6f4c933f2b4831e8a4a0188d5b2943b2,H5_log_load_blur_model_START,05c6ce94-20de-4e7a-88f5-b51433b126bf,加载模糊模型,2025-04-01 16:46:38.073000,2025-04-01 16:46:38.072900,"{""partner_id"": ""90""}",zox6f7eed,2.2.1.1
10,2862,None,d01f35945f0c343f85891b5b307c3b99,H5_log_load_blur_model_FAIL,05c6ce94-20de-4e7a-88f5-b51433b126bf,加载模糊模型失败,2025-04-01 16:46:42.767600,2025-04-01 16:46:42.767400,"{""partner_id"": ""90""}",zox6f7eed,2.2.1.1
11,2863,None,a73f9702523630ffa24918c8bbde9089,H5_log_106_model_START,05c6ce94-20de-4e7a-88f5-b51433b126bf,开始加载106模型,2025-04-01 16:46:42.801700,2025-04-01 16:46:42.801500,"{""partner_id"": ""90""}",zox6f7eed,2.2.1.1
12,2864,None,ddc228c877463aecabdceace9afdaa90,H5_log_106_model_SUCCESS,05c6ce94-20de-4e7a-88f5-b51433b126bf,加载106模型成功,2025-04-01 16:46:52.361600,2025-04-01 16:46:52.361400,"{""partner_id"": ""90""}",zox6f7eed,2.2.1.1
13,2865,None,69fa5d92e88e3c71a8e3496a06b9133d,H5_log_model_START,05c6ce94-20de-4e7a-88f5-b51433b126bf,开始加载人脸模型,2025-04-01 16:46:52.365000,2025-04-01 16:46:52.364800,"{""partner_id"": ""90""}",zox6f7eed,2.2.1.1
14,2866,None,3e21f627013a3596bcc03e91811470ac,H5_log_start_detect,05c6ce94-20de-4e7a-88f5-b51433b126bf,开始活体,2025-04-01 16:46:55.574200,2025-04-01 16:46:55.574000,"{""partner_id"": ""90""}",zox6f7eed,2.2.1.1
15,2867,None,0471984ec99330b79674cc055ca6159c,H5_log_tf_model_SUCCESS,05c6ce94-20de-4e7a-88f5-b51433b126bf,加载人脸模型成功,2025-04-01 16:46:55.577700,2025-04-01 16:46:55.577500,"{""partner_id"": ""90""}",zox6f7eed,2.2.1.1
16,2868,None,da33a7e5f571383a898aec8a2daa7ffa,H5_log_model_config_START,05c6ce94-20de-4e7a-88f5-b51433b126bf,人脸模型初始化开始,2025-04-01 16:46:55.580500,2025-04-01 16:46:55.580300,"{""partner_id"": ""90""}",zox6f7eed,2.2.1.1
17,2869,None,e1417d634c33362db46e884c0adeaa14,H5_log_model_config_SUCCESS,05c6ce94-20de-4e7a-88f5-b51433b126bf,人脸模型初始化成功,2025-04-01 16:46:55.825800,2025-04-01 16:46:55.825500,"{""partner_id"": ""90""}",zox6f7eed,2.2.1.1
18,2870,None,52e64c04a5e2383e8df846d979414a9a,H5_log_model_config_START,05c6ce94-20de-4e7a-88f5-b51433b126bf,关键点模型初始化开始,2025-04-01 16:46:55.869900,2025-04-01 16:46:55.869700,"{""partner_id"": ""90""}",zox6f7eed,2.2.1.1
19,2871,None,5e6e444837623ea4a813c3946ed0a3f0,H5_log_model_config_START,05c6ce94-20de-4e7a-88f5-b51433b126bf,关键点模型初始化成功,2025-04-01 16:46:56.391200,2025-04-01 16:46:56.391000,"{""partner_id"": ""90""}",zox6f7eed,2.2.1.1
20,2872,None,6e0df53ebd7836f1a94be8c447a92c77,H5_log_FACEINIT,05c6ce94-20de-4e7a-88f5-b51433b126bf,FACEINIT,2025-04-01 16:46:56.393800,2025-04-01 16:46:56.393700,"{""partner_id"": ""90""}",zox6f7eed,2.2.1.1
21,2873,None,5abdbb8747db3af1857f13592e455563,H5_log_closeMouth,05c6ce94-20de-4e7a-88f5-b51433b126bf,closeMouth,2025-04-01 16:46:56.997100,2025-04-01 16:46:56.996900,"{""partner_id"": ""90""}",zox6f7eed,2.2.1.1
22,2874,None,9e9b76edfcca385487272aad8af924be,H5_log_checkFaceCenter,05c6ce94-20de-4e7a-88f5-b51433b126bf,checkFaceCenter,2025-04-01 16:46:56.999700,2025-04-01 16:46:56.999500,"{""partner_id"": ""90""}",zox6f7eed,2.2.1.1
23,2875,None,6ee8a61c18af37c29ce8956a845dfb10,H5_log_checkFaceSize,05c6ce94-20de-4e7a-88f5-b51433b126bf,checkFaceSize,2025-04-01 16:46:57.001900,2025-04-01 16:46:57.001800,"{""partner_id"": ""90""}",zox6f7eed,2.2.1.1
24,2876,None,b91352917b7f3b839dad8415e85367d6,h5_log_FACECAPTUREREADY,05c6ce94-20de-4e7a-88f5-b51433b126bf,FACECAPTUREREADY,2025-04-01 16:46:57.004800,2025-04-01 16:46:57.004700,"{""partner_id"": ""90""}",zox6f7eed,2.2.1.1
25,2877,None,66d634864fbb3f599352af5fdcefcfe5,H5_log_Best_Img_w_h_kb,05c6ce94-20de-4e7a-88f5-b51433b126bf,"{""width"":270,""height"":360,""size"":""26.48kb""}",2025-04-01 16:46:57.999000,2025-04-01 16:46:57.998900,"{""partner_id"": ""90""}",zox6f7eed,2.2.1.1
26,2878,None,1c486a04533f3bbe8df3d2b8ce2d0d53,H5_log_action_START_BLINK,05c6ce94-20de-4e7a-88f5-b51433b126bf,开始眨眼,2025-04-01 16:46:58.491000,2025-04-01 16:46:58.490800,"{""partner_id"": ""90""}",zox6f7eed,2.2.1.1
27,2879,None,58435a5007263366bde31f64c2edcf94,H5_log_img_save_BEST,05c6ce94-20de-4e7a-88f5-b51433b126bf,最佳图片保存成功,2025-04-01 16:46:58.563700,2025-04-01 16:46:58.563500,"{""partner_id"": ""90""}",zox6f7eed,2.2.1.1
28,2880,None,8c2ab3328c6b3b3cb1a3f27593a2a439,H5_log_action_BLINK_SUCCESS,05c6ce94-20de-4e7a-88f5-b51433b126bf,眨眼成功,2025-04-01 16:46:59.533800,2025-04-01 16:46:59.533600,"{""partner_id"": ""90""}",zox6f7eed,2.2.1.1
29,2881,None,4598198596833ca6bacec49dd8ab4015,H5_log_img_save_BLINK,05c6ce94-20de-4e7a-88f5-b51433b126bf,眨眼图片保存成功,2025-04-01 16:46:59.700100,2025-04-01 16:46:59.699900,"{""partner_id"": ""90""}",zox6f7eed,2.2.1.1
30,2882,None,5045f7a4531f3872a351e64d151503d6,H5_log_twinkle_start,05c6ce94-20de-4e7a-88f5-b51433b126bf,开始闪烁,2025-04-01 16:47:01.894900,2025-04-01 16:47:01.894700,"{""partner_id"": ""90""}",zox6f7eed,2.2.1.1
31,2883,None,97fd55e170eb377d84fe1dbd624586cb,H5_log_flashing_start_frame_coun,05c6ce94-20de-4e7a-88f5-b51433b126bf,1232,2025-04-01 16:47:02.898000,2025-04-01 16:47:02.897900,"{""partner_id"": ""90""}",zox6f7eed,2.2.1.1
32,2884,None,01511291ed113383ac15664cc5afe57b,H5_log_twinkle_end,05c6ce94-20de-4e7a-88f5-b51433b126bf,结束闪烁,2025-04-01 16:47:05.910500,2025-04-01 16:47:05.910300,"{""partner_id"": ""90""}",zox6f7eed,2.2.1.1
33,2885,None,97eaa1b97554332ba6a6df9d1670a30b,H5_log_result_save_START,05c6ce94-20de-4e7a-88f5-b51433b126bf,保存活体结果-成功,2025-04-01 16:47:06.007300,2025-04-01 16:47:06.007200,"{""partner_id"": ""90""}",zox6f7eed,2.2.1.1
34,2886,None,d1b7f6c3901a36eeb0528ea20149a35f,H5_log_countdown,05c6ce94-20de-4e7a-88f5-b51433b126bf,28,2025-04-01 16:47:06.539400,2025-04-01 16:47:06.539200,"{""partner_id"": ""90""}",zox6f7eed,2.2.1.1
35,2887,None,15dfbb235bac3daaae5cc7780931daa0,H5_log_save_video_START,05c6ce94-20de-4e7a-88f5-b51433b126bf,开始保存压缩视频,2025-04-01 16:47:06.546400,2025-04-01 16:47:06.546300,"{""partner_id"": ""90""}",zox6f7eed,2.2.1.1
36,2888,None,7a8274e864c4374e85fc3e51f956f55d,H5_log_result_save_SUCCESS,05c6ce94-20de-4e7a-88f5-b51433b126bf,保存活体结果成功,2025-04-01 16:47:06.760700,2025-04-01 16:47:06.760500,"{""partner_id"": ""90""}",zox6f7eed,2.2.1.1
37,2889,None,11cf8f6bcaa03aaab01fb47f79776ba4,H5_log_save_video_SUCCESS,05c6ce94-20de-4e7a-88f5-b51433b126bf,保存压缩视频成功,2025-04-01 16:47:14.600000,2025-04-01 16:47:14.599800,"{""partner_id"": ""90""}",zox6f7eed,2.2.1.1
38,2890,None,facc920de705313fba30ccc198b743a0,H5_log_save_H5_file,05c6ce94-20de-4e7a-88f5-b51433b126bf,None,2025-04-01 16:47:14.756800,2025-04-01 16:47:14.756800,"{""partner_id"": ""90"", ""log_file_path"": ""/app/lo...",zox6f7eed,2.2.1.1
39,2891,None,ff2332e5af1d3f92b00dbe21007f051b,Log,05c6ce94-20de-4e7a-88f5-b51433b126bf,返回活体结果：isSuccess=true,2025-04-01 16:47:15.312200,2025-04-01 16:47:15.312000,None,zox6f7eed,AAR-2.0.2
40,2892,None,8ffa776ef1393ba8862b66df0f52020d,H5File,05c6ce94-20de-4e7a-88f5-b51433b126bf,None,2025-04-01 16:47:16.229400,2025-04-01 16:47:16.229400,"{""log_file_path"": ""/app/logs/8ffa776ef1393ba88...",zox6f7eed,AAR-2.0.2

In [8]:
print(oss.get_h5_file(oss_id= "e243c59203f33269a92bf43161423499.txt"))

进入活体次数：8
client_type pc-browser
selected_model mediapipe106
system_info mozilla/5.0 (macintosh; intel mac os x 10_15_7) applewebkit/537.36 (khtml, like gecko) chrome/134.0.0.0 safari/537.36
鉴权参数 partner-code:cv timestamp:1744101633898 token:fc571cad6976d62ef1817557faad549c userId:zoxxh2kia device:pc-browser
selected_model: mediapipe_detector_106
收集网络数据
network 4g
Adapter [object GPUAdapter]
Device [object GPUDevice]
Resource analysis [{"name":"https://testh5.liveness.goodproduct.tech/resource/mxHld/js/safari-nomodule-fix.js","type":"script","transferSizeKB":1,"durationMs":157},{"name":"https://testh5.liveness.goodproduct.tech/resource/mxHld/js/chunk-vendors.b891e2bf.js","type":"script","transferSizeKB":704,"durationMs":4125},{"name":"https://testh5.liveness.goodproduct.tech/resource/mxHld/js/app.38605135.js","type":"script","transferSizeKB":146,"durationMs":1777},{"name":"https://testh5.liveness.goodproduct.tech/resource/mxHld/css/app.7792c910.css","type":"link","transferSizeKB":7,"durationMs":164},{"name":"https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-wasm@4.20.0/dist/tf-backend-wasm.min.js","type":"script","transferSizeKB":31,"durationMs":1144},{"name":"https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@4/dist/tf.min.js","type":"script","transferSizeKB":317,"durationMs":1546},{"name":"https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-webgl@2.0.0-rc.4/dist/tf-backend-webgl.es2017.js","type":"script","transferSizeKB":77,"durationMs":1062},{"name":"https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-webgpu@4.22.0/dist/tf-backend-webgpu.min.js","type":"script","transferSizeKB":63,"durationMs":1386}]
监测到当前网络速度较慢,最多需要,S,请耐心等待
getUserMedia
here1
打开相机
480 camera_width 640 camera_height
medieRecoderFlag true
startCompression
开始录制
audioinput:  (ID: )
videoinput: FaceTime高清摄像头 (B6DF:451A) (ID: 7e5bd8e0e487ca1ffd5f3f056286dd405a5a078545a52830b06fb0276304d037)
audiooutput:  (ID: )
res [object Object],[object Object],[object Object]
color rgb(247,206,75)
color rgb(70,70,70)
color rgb(0,0,255)
wasm streaming compile failed: TypeError: Failed to execute 'compile' on 'WebAssembly': An argument must be provided, which must be a Response or Promise<Response> object
falling back to ArrayBuffer instantiation
falling back to ArrayBuffer instantiation 最新的报错
Backend wasm
17904 length
106_pfld loading 6232
wasm streaming compile failed: TypeError: Failed to execute 'compile' on 'WebAssembly': An argument must be provided, which must be a Response or Promise<Response> object
wasm streaming compile failed: TypeError: Failed to execute 'compile' on 'WebAssembly': An argument must be provided, which must be a Response or Promise<Response> object
falling back to ArrayBuffer instantiation
falling back to ArrayBuffer instantiation
falling back to ArrayBuffer instantiation 最新的报错
I0408 10:29:07.679000 1922656 gl_context.cc:386] GL version: 3.0 (OpenGL ES 3.0 (WebGL 2.0 (OpenGL ES 3.0 Chromium))), renderer: WebKit WebGL
W0408 10:29:07.681000 1922656 gl_context.cc:1072] OpenGL error checking is disabled
Graph successfully started running.
W0408 10:29:07.681000 1922656 gl_context.cc:1072] OpenGL error checking is disabled 最新的报错
detector loading 3659
开始活体
detectAndProcessFaces
18 : 29 7 结束加载模型的时间
人脸模型初始化开始
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
W0408 10:29:07.740000 1922656 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0408 10:29:07.740000 1922656 inference_feedback_manager.cc:121] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors. 最新的报错
dectector prediction 42
detector init 42
人脸模型初始化成功
box xMin 214 xMax 525 yMin 185 yMax 496
关键点模型初始化开始
106_plfd prediction 31
106_pfld init 32
关键点模型初始化成功
overall processing 86
face.length: 1
actionStatus FACEINIT
dectector prediction 8
box xMin 208 xMax 527 yMin 188 yMax 507
106_plfd prediction 19
overall processing 34
face.length: 1
checkFaceSize w h 0.4984375 0.6645833333333333
checkFaceCenter 0.1484375 0.22395833333333334
actionStatus FACESTILLREADY closeMouth
closeMouth 0.022568746851385504
startMouth 0.022568746851385504
checkAndBest: 6
actionStatus FACECAPTUREREADY
predict_proba 0.00
dectector prediction 8
box xMin 198 xMax 496 yMin 190 yMax 488
106_plfd prediction 19
overall processing 34
face.length: 1
startMouth 0.022464839064232797
checkAndBest: 3
predict_proba 0.00
dectector prediction 8
box xMin 200 xMax 495 yMin 193 yMax 488
106_plfd prediction 18
overall processing 31
face.length: 1
startMouth 0.026457965213520458
checkAndBest: 4
predict_proba 0.00
dectector prediction 8
box xMin 201 xMax 495 yMin 193 yMax 487
106_plfd prediction 17
overall processing 31
face.length: 1
startMouth 0.024935737062818222
checkAndBest: 2
predict_proba 0.00
dectector prediction 7
box xMin 201 xMax 493 yMin 195 yMax 487
106_plfd prediction 17
overall processing 30
face.length: 1
startMouth 0.019810651216587677
checkAndBest: 2
predict_proba 0.00
dectector prediction 7
box xMin 202 xMax 496 yMin 195 yMax 489
106_plfd prediction 17
overall processing 31
face.length: 1
startMouth 0.02089402645895777
checkAndBest: 2
predict_proba 0.00
dectector prediction 8
box xMin 202 xMax 496 yMin 197 yMax 491
106_plfd prediction 18
overall processing 31
face.length: 1
startMouth 0.0236138325670858
checkAndBest: 3
predict_proba 0.00
dectector prediction 8
box xMin 200 xMax 493 yMin 194 yMax 487
106_plfd prediction 18
overall processing 31
face.length: 1
startMouth 0.026107423442654935
checkAndBest: 3
predict_proba 0.00
dectector prediction 8
box xMin 202 xMax 494 yMin 197 yMax 489
106_plfd prediction 18
overall processing 31
face.length: 1
startMouth 0.02047712525558632
checkAndBest: 2
predict_proba 0.00
dectector prediction 8
box xMin 202 xMax 497 yMin 193 yMax 488
106_plfd prediction 17
overall processing 31
face.length: 1
startMouth 0.023227836334794746
checkAndBest: 2
predict_proba 0.00
dectector prediction 8
box xMin 199 xMax 496 yMin 189 yMax 486
106_plfd prediction 19
overall processing 32
face.length: 1
startMouth 0.023044309258375254
checkAndBest: 3
predict_proba 0.00
score 0.814
mouthScore:0.18,eyeScore:0.11,headScore:0.13,centerScore:0.08,newblurScore:0.25,orientationScore:0.07
mouth:0.023044309258375254,lefteye:0.1214047080151639,righteye:0.12353499398967506,header:0.32718310534762396
actionStatus FACEMOTIONREADY
info {"width":480,"height":640,"size":"63.30kb"}
dectector prediction 7
box xMin 198 xMax 494 yMin 192 yMax 488
106_plfd prediction 17
overall processing 31
w_ratio 0.4625 h_ratio 0.6166666666666667
face.length: 1
动作随机数 0
actionStatus FACEMOUTH
actionStatus FACEMOTIONREADY
dectector prediction 7
box xMin 201 xMax 493 yMin 196 yMax 488
106_plfd prediction 18
overall processing 31
w_ratio 0.45625 h_ratio 0.6083333333333333
face.length: 1
动作随机数 0
actionStatus FACEMOUTH
actionStatus FACEMOTIONREADY
dectector prediction 8
box xMin 201 xMax 493 yMin 196 yMax 488
106_plfd prediction 18
overall processing 30
w_ratio 0.45625 h_ratio 0.6083333333333333
face.length: 1
动作随机数 0
actionStatus FACEMOUTH
actionStatus FACEMOTIONREADY
dectector prediction 8
box xMin 202 xMax 493 yMin 197 yMax 488
106_plfd prediction 18
overall processing 31
w_ratio 0.4546875 h_ratio 0.60625
face.length: 1
动作随机数 0
actionStatus FACEMOUTH
dectector prediction 8
box xMin 201 xMax 493 yMin 196 yMax 487
106_plfd prediction 17
overall processing 30
w_ratio 0.45625 h_ratio 0.60625
face.length: 1
mouth 0.02361180667929801
actionStatus FACEMOTIONREADY
dectector prediction 8
box xMin 200 xMax 494 yMin 194 yMax 488
106_plfd prediction 19
overall processing 32
w_ratio 0.459375 h_ratio 0.6125
face.length: 1
动作随机数 0
actionStatus FACEMOUTH
actionStatus FACEMOTIONREADY
dectector prediction 8
box xMin 201 xMax 494 yMin 196 yMax 489
106_plfd prediction 18
overall processing 30
w_ratio 0.4578125 h_ratio 0.6104166666666667
face.length: 1
动作随机数 0
actionStatus FACEMOUTH
actionStatus FACEMOTIONREADY
dectector prediction 7
box xMin 200 xMax 493 yMin 195 yMax 487
106_plfd prediction 17
overall processing 30
w_ratio 0.4578125 h_ratio 0.6083333333333333
face.length: 1
动作随机数 0
actionStatus FACEMOUTH
actionStatus FACEMOTIONREADY
dectector prediction 8
box xMin 201 xMax 494 yMin 196 yMax 489
106_plfd prediction 18
overall processing 33
w_ratio 0.4578125 h_ratio 0.6104166666666667
face.length: 1
动作随机数 0
actionStatus FACEMOUTH
actionStatus FACEMOTIONREADY
dectector prediction 8
box xMin 200 xMax 495 yMin 193 yMax 487
106_plfd prediction 18
overall processing 30
w_ratio 0.4609375 h_ratio 0.6125
face.length: 1
动作随机数 0
actionStatus FACEMOUTH
actionStatus FACEMOTIONREADY
dectector prediction 8
box xMin 200 xMax 494 yMin 195 yMax 489
106_plfd prediction 17
overall processing 31
w_ratio 0.459375 h_ratio 0.6125
face.length: 1
动作随机数 0
actionStatus FACEMOUTH
actionStatus FACEMOTIONREADY
dectector prediction 11
box xMin 201 xMax 494 yMin 196 yMax 489
106_plfd prediction 18
overall processing 35
w_ratio 0.4578125 h_ratio 0.6104166666666667
face.length: 1
动作随机数 0
actionStatus FACEMOUTH
dectector prediction 8
box xMin 202 xMax 495 yMin 194 yMax 487
106_plfd prediction 25
overall processing 39
w_ratio 0.4578125 h_ratio 0.6104166666666667
face.length: 1
mouth 0.029093667963164357
dectector prediction 14
box xMin 201 xMax 494 yMin 195 yMax 488
106_plfd prediction 19
overall processing 45
w_ratio 0.4578125 h_ratio 0.6104166666666667
face.length: 1
mouth 0.024090070834964943
dectector prediction 9
box xMin 202 xMax 494 yMin 196 yMax 488
106_plfd prediction 19
overall processing 35
w_ratio 0.45625 h_ratio 0.6083333333333333
face.length: 1
mouth 0.026204943210702387
dectector prediction 9
box xMin 201 xMax 494 yMin 195 yMax 488
106_plfd prediction 19
overall processing 33
w_ratio 0.4578125 h_ratio 0.6104166666666667
face.length: 1
mouth 0.02642319743261526
dectector prediction 15
box xMin 200 xMax 494 yMin 192 yMax 486
106_plfd prediction 18
overall processing 44
w_ratio 0.459375 h_ratio 0.6125
face.length: 1
mouth 0.026327752111130993
dectector prediction 8
box xMin 202 xMax 495 yMin 196 yMax 489
106_plfd prediction 18
overall processing 32
w_ratio 0.4578125 h_ratio 0.6104166666666667
face.length: 1
mouth 0.025208742094185693
dectector prediction 8
box xMin 204 xMax 498 yMin 192 yMax 486
106_plfd prediction 20
overall processing 36
w_ratio 0.459375 h_ratio 0.6125
face.length: 1
mouth 0.022774498733025436
dectector prediction 10
box xMin 204 xMax 497 yMin 193 yMax 486
106_plfd prediction 20
overall processing 39
w_ratio 0.4578125 h_ratio 0.6104166666666667
face.length: 1
mouth 0.021441507710470813
dectector prediction 7
box xMin 201 xMax 493 yMin 194 yMax 486
106_plfd prediction 17
overall processing 29
w_ratio 0.45625 h_ratio 0.6083333333333333
face.length: 1
mouth 0.023928904026427285
dectector prediction 8
box xMin 203 xMax 497 yMin 191 yMax 485
106_plfd prediction 18
overall processing 31
w_ratio 0.459375 h_ratio 0.6125
face.length: 1
mouth 0.022234216517760978
dectector prediction 8
box xMin 203 xMax 497 yMin 191 yMax 485
106_plfd prediction 18
overall processing 31
w_ratio 0.459375 h_ratio 0.6125
face.length: 1
mouth 0.02337696031528152
dectector prediction 8
box xMin 200 xMax 491 yMin 190 yMax 481
106_plfd prediction 19
overall processing 31
w_ratio 0.4546875 h_ratio 0.60625
face.length: 1
mouth 0.02428483449203562
dectector prediction 8
box xMin 199 xMax 489 yMin 194 yMax 484
106_plfd prediction 23
overall processing 36
w_ratio 0.453125 h_ratio 0.6041666666666666
face.length: 1
mouth 0.019393358412232976
dectector prediction 8
box xMin 199 xMax 492 yMin 193 yMax 486
106_plfd prediction 18
overall processing 30
w_ratio 0.4578125 h_ratio 0.6104166666666667
face.length: 1
mouth 0.02656473934354876
dectector prediction 8
box xMin 199 xMax 493 yMin 195 yMax 489
106_plfd prediction 18
overall processing 32
w_ratio 0.459375 h_ratio 0.6125
face.length: 1
mouth 0.026743369103944894
dectector prediction 7
box xMin 200 xMax 492 yMin 193 yMax 485
106_plfd prediction 18
overall processing 30
w_ratio 0.45625 h_ratio 0.6083333333333333
face.length: 1
mouth 0.0300301943366335
dectector prediction 9
box xMin 200 xMax 497 yMin 187 yMax 484
106_plfd prediction 20
overall processing 34
w_ratio 0.4640625 h_ratio 0.61875
face.length: 1
mouth 0.028155673738300285
dectector prediction 8
box xMin 201 xMax 496 yMin 191 yMax 486
106_plfd prediction 18
overall processing 31
w_ratio 0.4609375 h_ratio 0.6145833333333334
face.length: 1
mouth 0.01746479999875855
dectector prediction 7
box xMin 202 xMax 497 yMin 189 yMax 484
106_plfd prediction 17
overall processing 30
w_ratio 0.4609375 h_ratio 0.6145833333333334
face.length: 1
mouth 0.02148847676074003
dectector prediction 8
box xMin 201 xMax 497 yMin 186 yMax 482
106_plfd prediction 17
overall processing 30
w_ratio 0.4625 h_ratio 0.6166666666666667
face.length: 1
mouth 0.026323651160415296
dectector prediction 8
box xMin 202 xMax 497 yMin 186 yMax 481
106_plfd prediction 18
overall processing 31
w_ratio 0.4609375 h_ratio 0.6145833333333334
face.length: 1
mouth 0.021673479435239704
dectector prediction 9
box xMin 201 xMax 495 yMin 191 yMax 485
106_plfd prediction 19
overall processing 32
w_ratio 0.459375 h_ratio 0.6125
face.length: 1
mouth 0.01942574878205337
dectector prediction 9
box xMin 202 xMax 493 yMin 189 yMax 480
106_plfd prediction 18
overall processing 31
w_ratio 0.4546875 h_ratio 0.60625
face.length: 1
mouth 0.021113974010799043
dectector prediction 9
box xMin 203 xMax 496 yMin 190 yMax 483
106_plfd prediction 18
overall processing 33
w_ratio 0.4578125 h_ratio 0.6104166666666667
face.length: 1
mouth 0.024063980633169613
dectector prediction 8
box xMin 206 xMax 494 yMin 195 yMax 483
106_plfd prediction 18
overall processing 30
w_ratio 0.45 h_ratio 0.6
face.length: 1
mouth 0.024743840022478703
dectector prediction 11
box xMin 204 xMax 501 yMin 189 yMax 486
106_plfd prediction 18
overall processing 49
w_ratio 0.4640625 h_ratio 0.61875
face.length: 1
mouth 0.027787059543317304
dectector prediction 7
box xMin 203 xMax 496 yMin 189 yMax 482
106_plfd prediction 18
overall processing 30
w_ratio 0.4578125 h_ratio 0.6104166666666667
face.length: 1
mouth 0.020463829426221346
dectector prediction 8
box xMin 202 xMax 498 yMin 187 yMax 483
106_plfd prediction 17
overall processing 29
w_ratio 0.4625 h_ratio 0.6166666666666667
face.length: 1
mouth 0.021556269698479024
dectector prediction 8
box xMin 202 xMax 496 yMin 192 yMax 486
106_plfd prediction 17
overall processing 29
w_ratio 0.459375 h_ratio 0.6125
face.length: 1
mouth 0.014935296750367056
dectector prediction 8
box xMin 202 xMax 494 yMin 191 yMax 483
106_plfd prediction 18
overall processing 31
w_ratio 0.45625 h_ratio 0.6083333333333333
face.length: 1
mouth 0.02105171039413482
dectector prediction 8
box xMin 202 xMax 494 yMin 191 yMax 483
106_plfd prediction 17
overall processing 31
w_ratio 0.45625 h_ratio 0.6083333333333333
face.length: 1
mouth 0.019782560552867395
dectector prediction 7
box xMin 201 xMax 494 yMin 190 yMax 483
106_plfd prediction 17
overall processing 31
w_ratio 0.4578125 h_ratio 0.6104166666666667
face.length: 1
mouth 0.021634761820433047
dectector prediction 7
box xMin 202 xMax 495 yMin 190 yMax 483
106_plfd prediction 18
overall processing 30
w_ratio 0.4578125 h_ratio 0.6104166666666667
face.length: 1
mouth 0.021253676132563154
dectector prediction 8
box xMin 203 xMax 496 yMin 193 yMax 486
106_plfd prediction 17
overall processing 29
w_ratio 0.4578125 h_ratio 0.6104166666666667
face.length: 1
mouth 0.023054193354012348
dectector prediction 8
box xMin 201 xMax 496 yMin 187 yMax 482
106_plfd prediction 18
overall processing 31
w_ratio 0.4609375 h_ratio 0.6145833333333334
face.length: 1
mouth 0.01906906198625784
dectector prediction 11
box xMin 202 xMax 494 yMin 189 yMax 481
106_plfd prediction 35
overall processing 54
w_ratio 0.45625 h_ratio 0.6083333333333333
face.length: 1
mouth 0.024980633241732723
dectector prediction 8
box xMin 200 xMax 493 yMin 189 yMax 482
106_plfd prediction 19
overall processing 36
w_ratio 0.4578125 h_ratio 0.6104166666666667
face.length: 1
mouth 0.02272381015574686
dectector prediction 8
box xMin 206 xMax 494 yMin 198 yMax 486
106_plfd prediction 17
overall processing 30
w_ratio 0.45 h_ratio 0.6
face.length: 1
mouth 0.022501310181039236
dectector prediction 7
box xMin 203 xMax 495 yMin 192 yMax 484
106_plfd prediction 18
overall processing 30
w_ratio 0.45625 h_ratio 0.6083333333333333
face.length: 1
mouth 0.020951714204698414
dectector prediction 8
box xMin 205 xMax 500 yMin 193 yMax 488
106_plfd prediction 17
overall processing 29
w_ratio 0.4609375 h_ratio 0.6145833333333334
face.length: 1
mouth 0.024405861057764572
dectector prediction 8
box xMin 204 xMax 499 yMin 187 yMax 482
106_plfd prediction 17
overall processing 29
w_ratio 0.4609375 h_ratio 0.6145833333333334
face.length: 1
mouth 0.025277125974673558
dectector prediction 8
box xMin 204 xMax 497 yMin 186 yMax 479
106_plfd prediction 17
overall processing 29
w_ratio 0.4578125 h_ratio 0.6104166666666667
face.length: 1
mouth 0.02315824928484365
dectector prediction 7
box xMin 203 xMax 498 yMin 188 yMax 483
106_plfd prediction 18
overall processing 30
w_ratio 0.4609375 h_ratio 0.6145833333333334
face.length: 1
mouth 0.020467524465922267
dectector prediction 8
box xMin 202 xMax 495 yMin 191 yMax 484
106_plfd prediction 18
overall processing 31
w_ratio 0.4578125 h_ratio 0.6104166666666667
face.length: 1
mouth 0.02081782960350227
dectector prediction 7
box xMin 202 xMax 496 yMin 194 yMax 488
106_plfd prediction 17
overall processing 30
w_ratio 0.459375 h_ratio 0.6125
face.length: 1
mouth 0.02530828981552506
dectector prediction 7
box xMin 204 xMax 500 yMin 195 yMax 491
106_plfd prediction 17
overall processing 29
w_ratio 0.4625 h_ratio 0.6166666666666667
face.length: 1
mouth 0.02379405996459116
dectector prediction 7
box xMin 203 xMax 500 yMin 192 yMax 489
106_plfd prediction 17
overall processing 29
w_ratio 0.4640625 h_ratio 0.61875
face.length: 1
mouth 0.030185255897296145
dectector prediction 7
box xMin 204 xMax 500 yMin 193 yMax 489
106_plfd prediction 19
overall processing 31
w_ratio 0.4625 h_ratio 0.6166666666666667
face.length: 1
mouth 0.024778625056224142
dectector prediction 8
box xMin 205 xMax 497 yMin 194 yMax 486
106_plfd prediction 17
overall processing 29
w_ratio 0.45625 h_ratio 0.6083333333333333
face.length: 1
mouth 0.025369022302792255
dectector prediction 8
box xMin 203 xMax 499 yMin 192 yMax 488
106_plfd prediction 18
overall processing 31
w_ratio 0.4625 h_ratio 0.6166666666666667
face.length: 1
mouth 0.022094883637353055
dectector prediction 8
box xMin 204 xMax 499 yMin 192 yMax 487
106_plfd prediction 17
overall processing 30
w_ratio 0.4609375 h_ratio 0.6145833333333334
face.length: 1
mouth 0.027894309936520794
dectector prediction 7
box xMin 201 xMax 497 yMin 193 yMax 489
106_plfd prediction 18
overall processing 32
w_ratio 0.4625 h_ratio 0.6166666666666667
face.length: 1
mouth 0.0238174697922587
dectector prediction 9
box xMin 201 xMax 499 yMin 190 yMax 488
106_plfd prediction 18
overall processing 32
w_ratio 0.465625 h_ratio 0.6208333333333333
face.length: 1
mouth 0.026760265270060923
dectector prediction 7
box xMin 202 xMax 497 yMin 194 yMax 489
106_plfd prediction 17
overall processing 29
w_ratio 0.4609375 h_ratio 0.6145833333333334
face.length: 1
mouth 0.028172572382452802
dectector prediction 7
box xMin 203 xMax 494 yMin 197 yMax 488
106_plfd prediction 17
overall processing 29
w_ratio 0.4546875 h_ratio 0.60625
face.length: 1
mouth 0.02366013519799466
dectector prediction 7
box xMin 202 xMax 493 yMin 197 yMax 488
106_plfd prediction 17
overall processing 30
w_ratio 0.4546875 h_ratio 0.60625
face.length: 1
mouth 0.028049215343608214
dectector prediction 8
box xMin 202 xMax 494 yMin 194 yMax 486
106_plfd prediction 17
overall processing 30
w_ratio 0.45625 h_ratio 0.6083333333333333
face.length: 1
mouth 0.02877909999682165
dectector prediction 8

In [9]:
# query = f"""
# SELECT *
# FROM cv.id_sdk_liveness_result
# WHERE create_time >= '2025-03-01'
# AND create_time < '2025-03-21'
# AND partner_id in (167)
# """
# liveness_data = connect.query(query=query)

# print(f"Shape : {liveness_data.shape}")
# liveness_data.drop_duplicates(subset= ['liveness_id'], inplace= True, keep= 'last')
# liveness_data['data'] =  liveness_data['data'].apply(lambda x: json.loads(x))
# liveness_data['ext_info'] =  liveness_data['ext_info'].apply(lambda x: json.loads(x))
# liveness_data['liveness_result_msg'] = liveness_data['ext_info'].apply(lambda x: x.get("errMsg", None))
# liveness_data['liveness_result_code'] = liveness_data['ext_info'].apply(lambda x: x.get("code", None))
# liveness_data['sdk_version'] = liveness_data['ext_info'].apply(lambda x: x.get("sdk_version", None))
# liveness_data['system'] = liveness_data['ext_info'].apply(lambda x: x.get("system", None))
# liveness_data['deviceInfo'] = liveness_data['ext_info'].apply(lambda x: x.get("deviceInfo", {}).get('source', None))
# liveness_result_df = liveness_data[['liveness_id', "create_time", 'partner_id', 'user_id', 'liveness_result_msg', 'liveness_result_code', 'sdk_version', 'system', 'deviceInfo']]
# liveness_count_df = liveness_result_df.groupby('user_id').size().reset_index(name = 'user_liveness_count')
# liveness_result_df = liveness_result_df.merge(right= liveness_count_df, on= 'user_id', how= 'inner')
# user_id_unique = str(tuple(liveness_result_df['user_id'].unique()))
# liveness_id_unique = str(tuple(liveness_result_df['liveness_id'].unique()))
# buried_detail_df = h5.get_buried_detail(liveness_id= liveness_id_unique)
# df = liveness_result_df.merge(buried_detail_df, on = 'liveness_id', how = 'left')
# df = df[df["deviceInfo"] == "android-app"].drop(columns = ["detector_type", "create_time", "user_liveness_count", "partner_id"]).reset_index(drop = True)
# df = df.drop_duplicates(subset= ['liveness_id'], keep= 'last').reset_index(drop = True)

In [10]:
df = pd.read_csv("./data/benchmark.csv")

In [11]:
df

,liveness_id,user_id,liveness_result_msg,liveness_result_code,sdk_version,system,deviceInfo,H5_file
0,9213c4fd-c829-46e7-9567-923ce4803cd1,99E954E9-9FAD-492B-B90D-A66EBE8A314B,DETECTSUCCESS-waktu habis,40003,2.2.0.14,h5,android-app,00272471392739e88ac13604d103b919.txt
1,68ad951c-ed33-43c9-8020-64ef68c6a24a,1169736,ACTIONDOWN-waktu habis,40003,2.2.0.14,h5,android-app,8c5ed90319a5373b82c49860e80da77c.txt
2,fbb452bc-b157-4b83-94c8-42089a1a3c4c,1169989,Deteksi liveness sukses,200,2.2.0.14,h5,android-app,5a56e20ca2f83350ad17d0c6ff7a6c69.txt
3,8b801033-5d18-4f0c-83a7-efe2a7ea9d5c,1170047,Deteksi liveness sukses,200,2.2.0.14,h5,android-app,7176dab2763b34f0941af38363ccd63c.txt
4,723744ef-b9c1-4490-834d-3ec5e47ec3f6,99E954E9-9FAD-492B-B90D-A66EBE8A314B,Deteksi liveness sukses,200,2.2.0.14,h5,android-app,eea35773d7a730f5b3cdcf3e36ab6541.txt
...,...,...,...,...,...,...,...,...
25981,ebb819ca-784a-4fe8-8b7d-9a5bc0e158f9,1373173,Deteksi liveness sukses,200,2.2.0.14,h5,android-app,c09c6d37eb3333e8a5209e75abce88b2.txt
25982,e37304ca-61fa-43f6-a1f4-2c03aeac589c,1346069,Deteksi liveness sukses,200,2.2.0.14,h5,android-app,cf2f67f4d87f3e959fc82706e8d9d9ef.txt
25983,954f8c11-f057-488e-82f2-5d35f6e9eda4,846367,FACENODEFINE-waktu habis,40003,2.2.0.14,h5,android-app,50d0cf15e1d03741bec2570f1070f1d1.txt
25984,795563e2-7f74-4a86-8f72-0054eb5f6667,1373294,Deteksi liveness sukses,200,2.2.0.14,h5,android-app,c1af16d38bff3d2fa5933623c221c3e1.txt
25985,8b9f7c55-e508-46f9-8825-92a417723ce9,1373256,Deteksi liveness sukses,200,2.2.0.14,h5,android-app,1759a3d64565384682b2a810cd52f6ae.txt

In [12]:
new_column = ['client', 'backend', 'detector_loading', "pfld_106_loading", "detector_init", "pfld_106_init", "detector_prediction", "pfld_106_prediction", "overall_processing"]
df = multiprocess_row(df = df, new_columns = new_column, number_worker = 8)

Process SpawnPoolWorker-3:
Process SpawnPoolWorker-1:
Traceback (most recent call last):
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'process_row' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'process_row' on <module '__main__' (built-in)>
Process SpawnPoolWorker-2:
Traceback (most recent call last):
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'process_row' on <module '__main__' (built-in)>
Process SpawnPoolWorker-6:
Traceback (most recent call last):
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'process_row' on <module '__main__' (built-in)>
Process SpawnPoolWorker-4:
Traceback (most recent call last):
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'process_row' on <module '__main__' (built-in)>
Process SpawnPoolWorker-5:
Traceback (most recent call last):
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'process_row' on <module '__main__' (built-in)>
Process SpawnPoolWorker-7:
Traceback (most recent call last):
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'process_row' on <module '__main__' (built-in)>
Process SpawnPoolWorker-8:
Traceback (most recent call last):
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'process_row' on <module '__main__' (built-in)>
Process SpawnPoolWorker-9:
Traceback (most recent call last):
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'process_row' on <module '__main__' (built-in)>
Process SpawnPoolWorker-10:
Traceback (most recent call last):
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'process_row' on <module '__main__' (built-in)>
Process SpawnPoolWorker-11:
Traceback (most recent call last):
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'process_row' on <module '__main__' (built-in)>
Process SpawnPoolWorker-12:
Traceback (most recent call last):
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'process_row' on <module '__main__' (built-in)>
Process SpawnPoolWorker-13:
Traceback (most recent call last):
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'process_row' on <module '__main__' (built-in)>
Process SpawnPoolWorker-14:
Traceback (most recent call last):
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'process_row' on <module '__main__' (built-in)>
Process SpawnPoolWorker-15:
Traceback (most recent call last):
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'process_row' on <module '__main__' (built-in)>
Process SpawnPoolWorker-16:
Traceback (most recent call last):
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'process_row' on <module '__main__' (built-in)>
Process SpawnPoolWorker-17:
Traceback (most recent call last):
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'process_row' on <module '__main__' (built-in)>
Process SpawnPoolWorker-18:
Traceback (most recent call last):
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'process_row' on <module '__main__' (built-in)>
Process SpawnPoolWorker-19:
Traceback (most recent call last):
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'process_row' on <module '__main__' (built-in)>
Process SpawnPoolWorker-20:
Traceback (most recent call last):
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'process_row' on <module '__main__' (built-in)>
Process SpawnPoolWorker-21:
Traceback (most recent call last):
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'process_row' on <module '__main__' (built-in)>
Process SpawnPoolWorker-22:
Traceback (most recent call last):
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'process_row' on <module '__main__' (built-in)>
Process SpawnPoolWorker-23:
Traceback (most recent call last):
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'process_row' on <module '__main__' (built-in)>
Process SpawnPoolWorker-24:
Traceback (most recent call last):
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'process_row' on <module '__main__' (built-in)>
Process SpawnPoolWorker-25:
Traceback (most recent call last):
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'process_row' on <module '__main__' (built-in)>
Process SpawnPoolWorker-26:
Traceback (most recent call last):
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'process_row' on <module '__main__' (built-in)>
Process SpawnPoolWorker-27:
Traceback (most recent call last):
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'process_row' on <module '__main__' (built-in)>
Process SpawnPoolWorker-28:
Traceback (most recent call last):
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/sheejiawei/.pyenv/versions/3.10.14/lib/python3.10/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'process_row' on <module '__main__' (built-in)>
Process SpawnPoolWorker-29:

KeyboardInterrupt:

In [ ]:
df.to_csv("./data/processed_benchmark.csv", index= False)